#!/bin/bash

for (( i=1; i<=100; i++ ))
do
   echo ""
done

echo "##########################################################################################"
echo "#                                                                                        #"
echo "#                                   Simulation Script                                    #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo "#                                                                                        #"
echo "#  Version 1.0                                                                           #"
echo "#  Jun. 14, 2014                                                                         #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo ""
echo ""
echo ""
echo ""

mkdir -p waves
rm -rf ./waves/*

temp_v_list1=`find ../tb -type f -name "*.sv"`
temp_v_list2=`find ../../rtl -type f -name "*.sv"`
temp_v_list3=`find ../../rtl/pkg -type f -name "*.sv"`
temp_v_list="${temp_v_list1} ${temp_v_list2} ${temp_v_list3}"
for f in ${temp_v_list}
do
    cp -f $f ./waves/
done
temp_v_list=`find ./waves -type f -name "*.sv"`
timescale="1ns/1ps"
for f in ${temp_v_list}
do
    tscale=`cat ${f} | grep "timescale"`
    tscale=`echo ${tscale} | cut -d ' ' -f2`
    if [ "$tscale" != "" ]; then
        timescale="$tscale"
    fi
done
for f in ${temp_v_list}
do
    tscale=`cat ${f} | grep "timescale"`
    tscale=`echo ${tscale} | cut -d ' ' -f2`
    if [ "$tscale" != "" ]; then
        echo "" > ./waves/temp.v
        cat $f >> ./waves/temp.v
        mv ./waves/temp.v $f
    else
        echo "\`timescale $timescale" > ./waves/temp.v
        cat ${f} >> ./waves/temp.v
        mv ./waves/temp.v ${f}
    fi
done
cp ../*.dat ../tests/*.dat ./waves/
cd ./waves
vlist=""
for f in ${temp_v_list}
do
    f1=`echo $f | cut -d '/' -f3`
    if [[ "$f1" == *"_pkg.sv" ]]; then
        vlist="$f1 $vlist"
    else
        vlist="$vlist $f1"
    fi
done
echo $vlist
vcs -top tp1_tb \
    +incdir+../rtl \
    $vlist \
    -l vcs.log \
    +vcs+lic+wait \
    +warn=all \
    +lint=all \
    -sverilog \
    -debug

echo "dump  -add / -aggregates -depth 0" > simv.tcl
echo "run" >> simv.tcl
echo "quit" >> simv.tcl
./simv -ucli \
    -do simv.tcl \
    -l sim.log

mkdir ../temp
mv sim.log ../temp/sim.log
mv vcs.log ../temp/vcs.log
mv inter.vpd ../temp/microprocessor.vpd
rm -rf *
mv ../temp/* ./
rm -rf ../temp
cd ..

echo ""
