#!/bin/bash
#####################################################################################
#
# Description:
# ------------
#
# Run IC Compiler Script.
#
#####################################################################################

for (( i=1; i<=100; i++ ))
do
   echo ""
done
clear

echo "##########################################################################################"
echo "#                                                                                        #"
echo "#                             Run Synopsys IC Compiler Script                            #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo "#                                                                                        #"
echo "#  Version 1.0                                                                           #"
echo "#  Jun. 14, 2014                                                                         #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo ""
echo ""
echo ""

function command_sintax {
   echo "   Usage:"
   echo "         ./run_icc [options]"
   echo ""
   echo "   Options:"
   echo "         -help       Display this information."
   echo "         -interact   Open the IC Compiler in interactive mode."
   echo ""
   echo ""
   echo ""
}

if [ $# == 1 ] && [ $1 == "-help" ]; then
   command_sintax
   exit
fi

interact=0

prev_arg=""
for ARG in "$@"
do
   opt=`echo ${ARG}`
   if [ "${prev_arg}" == "-file" ]; then
      tcl_file=${opt}
   else
      case ${opt} in
         "-interact")
            interact=1
         ;;
         *)
            echo "ERROR: Option '${cmd}' unknown."
            echo ""
            echo ""
            command_sintax
            exit
         ;;
      esac
   fi
   prev_arg=${opt}
done

tcl_path="../../scripts/pnr/"
tcl_file="pnr.tcl"
mkdir -p temp
cat "${tcl_path}${tcl_file}" > temp/temp.tcl

rm ../../dgen/pnr/reports/*

echo ""
echo "INFO: Grabing IC Compiler license..."
echo ""

export SYNOPSYS=${DCOMPILER_PATH}
export SNPSLMD_LICENSE_FILE=1718@credenciales
ICC_PATH=/usr/synopsys/J-2014.09-SP5-1/ic_compiler

cd temp
if [ ${interact} == 1 ]; then
   ${ICC_PATH}/bin/icc_shell -output_log_file "../../../dgen/pnr/reports/icc.log"
else
   ${ICC_PATH}/bin/icc_shell -gui -x "source temp.tcl" -output_log_file "../../../dgen/pnr/reports/icc.log"
fi
cd ..
rm -rf temp
