#!/bin/bash
#####################################################################################
#
# Description:
# ------------
#
# Run Synopsys Design Compiler Script.
#
#####################################################################################

for (( i=1; i<=100; i++ ))
do
   echo ""
done
clear

echo "##########################################################################################"
echo "#                                                                                        #"
echo "#                           Run Synopsys Design Compiler Script                          #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo "#                                                                                        #"
echo "#  Version 1.0                                                                           #"
echo "#  Jun. 14, 2014                                                                         #"
echo "#                                                                                        #"
echo "##########################################################################################"
echo ""
echo ""
echo ""

function command_sintax {
   echo "   Usage:"
   echo "         ./run_dcompiler [options]"
   echo ""
   echo "   Options:"
   echo "         -help       Display this information."
   echo "         -interact   Open the Design Compiler in interactive mode."
   echo ""
   echo ""
   echo ""
}

if [ $# == 1 ] && [ $1 == "-help" ]; then
   command_sintax
   exit
fi

interact=0

prev_arg=""
for ARG in "$@"
do
   opt=`echo ${ARG}`
   if [ "${prev_arg}" == "-file" ]; then
      tcl_file=${opt}
   else
      case ${opt} in
         "-interact")
            interact=1
         ;;
         *)
            echo "ERROR: Option '${cmd}' unknown."
            echo ""
            echo ""
            command_sintax
            exit
         ;;
      esac
   fi
   prev_arg=${opt}
done

tcl_path="../../scripts/syn/"
tcl_file="syn.tcl"
mkdir -p temp
cat "${tcl_path}${tcl_file}" > temp/temp.tcl

echo ""
echo "INFO: Grabing Design Compiler license..."
echo ""

rm ../../dgen/syn/reports/*

export SYNOPSYS=${DCOMPILER_PATH}
export SNPSLMD_LICENSE_FILE=1718@credenciales
DCOMPILER_PATH=/usr/synopsys/J-2014.09-SP5-3/design_compiler

cd temp
if [ ${interact} == 1 ]; then
   ${DCOMPILER_PATH}/bin/dc_shell -topo -no_gui -output_log_file "../../../dgen/syn/reports/dcompiler.log"
else
   ${DCOMPILER_PATH}/bin/dc_shell -topo -no_gui -x "source temp.tcl" -output_log_file "../../../dgen/syn/reports/dcompiler.log"
fi
cd ..
rm -rf temp
